#include "hal_data.h"
#include "usr_nmi_handler.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */
        fsp_err_t err;

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);

        err = R_BSP_GroupIrqWrite(BSP_GRP_IRQ_MPU_STACK, user_nmi_handler);
        if (FSP_SUCCESS != err)
        {
            __BKPT(0);
        }

        //R_QSPI_Open(&g_qspi0_ctrl, &g_qspi0_cfg);

        {
            err = R_QSPI_Open(&g_qspi0_ctrl, &g_qspi0_cfg);
            if (FSP_SUCCESS != err)
            {
                __BKPT(0);
            }


            uint8_t   data;
            uint8_t command[3] ={0x01, 0x40, 0x00};

            /* Write enable command */
            err = R_QSPI_DirectWrite(&g_qspi0_ctrl, &(g_qspi0_cfg.write_enable_command), 1, false);
            assert(FSP_SUCCESS == err);

            R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MICROSECONDS);

            /* Write status register */
            err = R_QSPI_DirectWrite(&g_qspi0_ctrl, &command[0], 3, false);
            assert(FSP_SUCCESS == err);

            R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MICROSECONDS);

            /* Read a status register. */
            err  = R_QSPI_DirectWrite(&g_qspi0_ctrl, &(g_qspi0_cfg.status_command), 1, true);
            assert(FSP_SUCCESS == err);

            R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MICROSECONDS);

            err = R_QSPI_DirectRead(&g_qspi0_ctrl, &data, 2);
            assert(FSP_SUCCESS == err);
        }

    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
